	const TEOF <- 0
	const TIDENTIFIER <- 1
	const TOPERATOR <- 2
	const TLPAREN <- 3
	const TRPAREN <- 4
	const TLSQUARE <- 5
	const TRSQUARE <- 6
	const TLCURLY <- 7
	const TRCURLY <- 8
	const TDOLLAR <- 9
	const TDOT <- 10
	const TDOTSTAR <- 11
	const TDOTQUESTION <- 12
	const TCOMMA <- 13
	const TCOLON <- 14
	const TSEMI <- 15
	const TINTEGERLITERAL <- 16
	const TREALLITERAL <- 17
	const TCHARACTERLITERAL <- 18
	const TSTRINGLITERAL <- 19
	const OAND <- 20
	const OASSIGN <- 21
	const OCONFORMSTO <- 22
	const ODIVIDE <- 23
	const OEQUAL <- 24
	const OGREATER <- 25
	const OGREATEREQUAL <- 26
	const OIDENTITY <- 27
	const OLESS <- 28
	const OLESSEQUAL <- 29
	const OMINUS <- 30
	const OMOD <- 31
	const ONEGATE <- 32
	const ONOT <- 33
	const ONOTEQUAL <- 34
	const ONOTIDENTITY <- 35
	const OOR <- 36
	const OPLUS <- 37
	const ORETURNS <- 38
	const OTIMES <- 39
	const KAND <- 40
	const KAS <- 41
	const KASSERT <- 42
	const KAT <- 43
	const KAWAITING <- 44
	const KATTACHED <- 45
	const KBEGIN <- 46
	const KBUILTIN <- 47
	const KBY <- 48
	const KCHECKPOINT <- 49
	const KCLOSURE <- 50
	const KCODEOF <- 51
	const KCLASS <- 52
	const KCONST <- 53
	const KELSE <- 54
	const KELSEIF <- 55
	const KEND <- 56
	const KENUMERATION <- 57
	const KEXIT <- 58
	const KEXPORT <- 59
	const KEXTERNAL <- 60
	const KFAILURE <- 61
	const KFALSE <- 62
	const KFIELD <- 63
	const KFIX <- 64
	const KFOR <- 65
	const KFORALL <- 66
	const KFROM <- 67
	const KFUNCTION <- 68
	const KIF <- 69
	const KIMMUTABLE <- 70
	const KINITIALLY <- 71
	const KISFIXED <- 72
	const KISLOCAL <- 73
	const KLOCATE <- 74
	const KLOOP <- 75
	const KMONITOR <- 76
	const KMOVE <- 77
	const KNAMEOF <- 78
	const KNEW <- 79
	const KNIL <- 80
	const KOBJECT <- 81
	const KOP <- 82
	const KOPERATION <- 83
	const KOR <- 84
	const KPRIMITIVE <- 85
	const KPROCESS <- 86
	const KRECORD <- 87
	const KRECOVERY <- 88
	const KREFIX <- 89
	const KRESTRICT <- 90
	const KRETURN <- 91
	const KRETURNANDFAIL <- 92
	const KSELF <- 93
	const KSIGNAL <- 94
	const KSUCHTHAT <- 95
	const KSYNTACTICTYPEOF <- 96
	const KTHEN <- 97
	const KTO <- 98
	const KTRUE <- 99
	const KTYPEOBJECT <- 100
	const KTYPEOF <- 101
	const KUNFIX <- 102
	const KUNAVAILABLE <- 103
	const KVAR <- 104
	const KVIEW <- 105
	const KVISIT <- 106
	const KWAIT <- 107
	const KWHEN <- 108
	const KWHILE <- 109
	const KWHERE <- 110
