#
# Random CCALL makefile
#

SRCS = 
INCS = random.h

default: all

all:

# begin --- Emerald interpreter targets ---

export: ../trandom.h

../trandom.h: $(INCS)
	cat $(INCS) >$@

clean:

# end --- Emerald interpreter targets ---

# EOF
