#define JOPEN     0
#define JCLOSE    1
#define JREAD     2
#define JWRITE    3
#define JSEEK     4
#define GETSTDIN  5
#define GETSTDOUT 6
#define GETTOD    7
#define GETLNN    8
#define GETNAME   9
#define GETNODE  10
#define JUNLINK  11
#define GETACTIVENODES	12
#define GETALLNODES	13
#define JDELAY 14
#define JISATTY 15
#define JFOPEN     16
#define FUNGETCHAR 17
#define FGETCHAR 18
#define FGETSTRING 19
#define FEOS 20
#define FCLOSE    21
#define FISATTY 22
#define FPUTCHAR 23
#define FPUTINT 24
#define FWRITEINT 25
#define FPUTREAL 26
#define FPUTSTRING 27
#define FFLUSH 28
#define DECODEMSG 29
#define JTRACE 30
#define ISLOCAL 31
#define FGETSTRINGV 32
#define JMOVE 33
#define JFIX 34
#define JUNFIX 35
#define JREFIX 36
#define JLOCATE 37
#define ISFIXED 38
#define JGETINCARNATIONTIME 39
#define JGETLOADAVERAGE 40
#define JSYS_OPS 41
