/*
 * cctab.h
 *
 * THIS FILE IS AUTOMATICALLY GENERATED.  DO NOT EDIT.
 */

#ifndef _EMERALD_CCALLTAB_H
#define _EMERALD_CCALLTAB_H 1

typedef int (*ccallFunction)(void);

typedef struct CCallDescriptor {
  ccallFunction ccFunction;
  char* ccName;
  char* ccArgTemplate;
} CCallDescriptor;

extern CCallDescriptor *ccalltable[];
#define EMSTREAM 0
extern int streamOpen(void);
#define EMS_OPEN 0
extern int streamClose(void);
#define EMS_CLOSE 1
extern int streamEos(void);
#define EMS_EOS 2
extern int streamIsAtty(void);
#define EMS_ISATTY 3
extern int streamGetChar(void);
#define EMS_GETC 4
extern int streamUngetChar(void);
#define EMS_UNGETC 5
extern int streamGetString(void);
#define EMS_GETS 6
extern int streamFillVector(void);
#define EMS_FILLV 7
extern int streamPutChar(void);
#define EMS_PUTC 8
extern int streamPutInt(void);
#define EMS_PUTI 9
extern int streamWriteInt(void);
#define EMS_WRITEI 10
extern int streamPutReal(void);
#define EMS_PUTF 11
extern int streamPutString(void);
#define EMS_PUTS 12
extern int streamFlush(void);
#define EMS_FLUSH 13
extern int streamBind(void);
#define EMS_BIND 14
extern int streamAccept(void);
#define EMS_ACCEPT 15
extern int streamRawRead(void);
#define EMS_RAWREAD 16
#define STRING 1
extern int charIsAlpha(void);
#define EMCH_ISALPHA 0
extern int charIsUpper(void);
#define EMCH_ISUPPER 1
extern int charIsLower(void);
#define EMCH_ISLOWER 2
extern int charIsDigit(void);
#define EMCH_ISDIGIT 3
extern int charIsXdigit(void);
#define EMCH_ISXDIGIT 4
extern int charIsAlnum(void);
#define EMCH_ISALNUM 5
extern int charIsSpace(void);
#define EMCH_ISSPACE 6
extern int charIsPunct(void);
#define EMCH_ISPUNCT 7
extern int charIsPrint(void);
#define EMCH_ISPRINT 8
extern int charIsGraph(void);
#define EMCH_ISGRAPH 9
extern int charIsCntrl(void);
#define EMCH_ISCNTRL 10
extern int charToUpper(void);
#define EMCH_TOUPPER 11
extern int charToLower(void);
#define EMCH_TOLOWER 12
extern int stringIndex(void);
#define EMST_INDEX 13
extern int stringRIndex(void);
#define EMST_RINDEX 14
extern int stringSpan(void);
#define EMST_SPAN 15
extern int stringCSpan(void);
#define EMST_CSPAN 16
extern int stringStr(void);
#define EMST_STR 17
#define RAND 2
extern int random(void);
#define RANDOM 0
extern int srandom(void);
#define SRANDOM 1
#define MISK 3
extern int die(void);
#define UEXIT 0
extern int mgetenv(void);
#define UGETENV 1
extern int opendir(void);
#define UOPENDIR 2
extern int mreaddir(void);
#define UREADDIR 3
extern int closedir(void);
#define UCLOSEDIR 4
#endif
