#
# Miscellaneous CCALL makefile
#

SRCS = hello.c
INCS = hello.h exit.h

default: all

all:

# begin --- Emerald interpreter targets ---

export: ../misc.h

../misc.h: $(INCS)
	cat $(INCS) >$@

clean:

# end --- Emerald interpreter targets ---

# EOF
