#
# Miscellaneous CCALL makefile
#

SRCS = 
INCS = bani.h

default: all

all:

# begin --- Emerald interpreter targets ---

export: ../bani.h

../bani.h: $(INCS)
	cat $(INCS) >$@

clean:

# end --- Emerald interpreter targets ---

# EOF
