#
# Miscellaneous CCALL makefile
#

SRCS = 
INCS = misk.h

default: all

all:

# begin --- Emerald interpreter targets ---

export: ../misk.h

../misk.h: $(INCS)
	cat $(INCS) >$@

clean:

# end --- Emerald interpreter targets ---

# EOF
