#
# X library CCALL Makefile
#

SRCS = 
INCS = xliba.h

default: all

all:

# begin --- Emerald interpreter targets ---

export: ../xliba.h

../xliba.h: $(INCS)
	cat $(INCS) >$@

clean:

# end --- Emerald interpreter targets ---

# EOF
