#
# Random CCALL makefile
#

SRCS = 
INCS = rand.h

default: all

all:

# begin --- Emerald interpreter targets ---

export: ../rand.h

../rand.h: $(INCS)
	cat $(INCS) >$@

clean:

# end --- Emerald interpreter targets ---

# EOF
