#!/bin/csh -f
#
# @(#)MAKETOKENNAMES	1.3  3/17/89
#
ed - << theend
0r em_ecomp.y
v/^%token/d
1,\$s;^%token[ 	]*\([^ 	]*\)[^"]*"\([^"]*\)".*;  "\2";
1,\$s;\$;,;
\$s/,\$//
1i
const tokenNameTable <- {
.
\$a
}
.
w tokNames.m
q
theend
